---
- name: "CAUTION: the following users will have passwordless sudo rights"
  debug: var=sudo_users
  when: sudo_users is defined

- name: enable passwordless sudo
  lineinfile: dest=/etc/sudoers.d/{{item}} regexp="^{{item}}" line="{{item}} ALL=NOPASSWD:ALL" state=present create=yes mode=0440
  with_items: sudo_users
  when: sudo_users is defined
